### ISSUE TITLE
Missing Coco.atg file

### ISSUE THREAD

**Issue by ColMcp** [mgriebling/Coco#1]
Thank you for porting Coco/R to Swift!

The README for the project mentions "the included Coco.atg attributed grammar file". I was hoping to study it as an example of a Swift-specific Coco/R grammar but I don't see it anywhere. Could it be made available please?

**Comment by mgriebling** [comment]
Fixed.  Somehow the Coco.atg file was inadvertently omitted during the previous update.

**Comment by ColMcp** [comment]
Thank you.

**Comment by mgriebling** [comment]
BTW, a simpler intro to the Swift version of Coco may be the Taste compiler which I also ported to Swift.

**Comment by ColMcp** [comment]
Thanks again!
